const actionTypes = {
  RESET_BOARD: 'RESET_BOARD',
  SQUARE_CLICKED_IS_MINE: 'SQUARE_CLICKED_IS_MINE',
  SQUARE_CLICKED_IS_NOT_VISIBLE: 'SQUARE_CLICKED_IS_NOT_VISIBLE',
};

export default actionTypes;
